import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity   = 0.8
blur      = true

[font]
size = 16

[font.normal]
family = "Hack Nerd Font Mono"
style  = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style  = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style  = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style  = "Italic"
